---
hera_home: "{{ lookup('env', 'HERA_HOME') }}"
hera_debug: "{{ lookup('env', 'HERA_DEBUG') | default(False) }}"
podman_image: "{{ lookup('ansible.builtin.env', 'HERA_MOLECULE_SLAVE_IMAGE') | default('podman_image', 'localhost/molecule-slave-9') }}"
hera_ssh_username: "{{ lookup('ansible.builtin.env', 'HERA_USERNAME') | default('jenkins', 'jenkins') }}"
hera_molecule_slave_sshd_port: "{{ lookup('env', 'BUILD_MOLECULE_SLAVE_SSHD_PORT') | default('undefined') }}"
workdir: "{{ lookup('env', 'WORKDIR') }}"
job_name: "{{ lookup('env', 'JOB_NAME') | default('ansible') }}-slave"
wait_for_sshd: 60
