---
hera_home: "{{ lookup('env', 'HERA_HOME') }}"
hera_debug: "{{ lookup('env', 'HERA_DEBUG') | default(False) }}"
podman_image: 'e3485eef2807420841381ff2d1062b30bf696c536a1309d368365904b9a7663f'
hera_molecule_slave_sshd_port: "{{ lookup('env', 'BUILD_MOLECULE_SLAVE_SSHD_PORT') | default('undefined') }}"
workdir: "{{ lookup('env', 'WORKDIR') }}"
job_name: "{{ lookup('env', 'JOB_NAME') | default('ansible') }}-slave"
wait_for_sshd: 60
