---
- name: Create
  hosts: all
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  collections:
    - middleware_automation.eris
  tasks:
    - ansible.builtin.include_role:
        name: eris_hera_create
