---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - middleware_automation.eris
  tasks:
    - ansible.builtin.include_role:
        name: eris_hera_destroy
