---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - middleware_automation.eris
  roles:
    - eris_hera_destroy
  tasks:
